# Generated by Django 6.0.5 on 2026-05-27 15:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CBT_Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('duration_minutes', models.IntegerField(default=60)),
                ('total_questions', models.IntegerField(default=1)),
                ('passing_score', models.IntegerField(default=70)),
                ('auto_save_interval_seconds', models.IntegerField(default=30)),
                ('token_refresh_before_expiry_seconds', models.IntegerField(default=300)),
                ('is_published', models.BooleanField(default=False)),
                ('show_answers_after', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('track', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('both', 'Both')], max_length=20)),
                ('credits', models.IntegerField(default=3)),
                ('duration_weeks', models.IntegerField(default=8)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CBT_Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('drag_drop_3d', 'Drag & Drop 3D'), ('short_answer', 'Short Answer')], max_length=20)),
                ('model_url', models.URLField(blank=True)),
                ('correct_answer', models.JSONField()),
                ('point_value', models.IntegerField(default=1)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.cbt_quiz')),
            ],
            options={
                'ordering': ['quiz', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Lab_Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('required_hardware', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_projects', to='core.module')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.AddField(
            model_name='cbt_quiz',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='core.module'),
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('partner_since', models.DateField(auto_now_add=True)),
                ('primary_contact_email', models.EmailField(max_length=254)),
                ('tracks_offered', models.CharField(choices=[('primary', 'Primary (Ages 2-10)'), ('secondary', 'Secondary (Ages 11-17)'), ('both', 'Both Primary & Secondary')], default='both', max_length=20)),
                ('student_capacity', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('subeb_verified', models.BooleanField(default=False)),
                ('subeb_verified_date', models.DateField(blank=True, null=True)),
                ('hardware_inventory_verified', models.BooleanField(default=False)),
                ('total_donations_naira', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='core_school_is_acti_2e0f0f_idx'), models.Index(fields=['subeb_verified'], name='core_school_subeb_v_a57a3e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('specialization', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('can_grade', models.BooleanField(default=True)),
                ('can_deploy_cbt', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructors', to='core.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('track', models.CharField(choices=[('primary', 'Primary (Ages 2-10)'), ('secondary', 'Secondary (Ages 11-17)'), ('both', 'Both Primary & Secondary')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='active', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('max_students', models.IntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cohorts_taught', to='core.instructor')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohorts', to='core.school')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('track', models.CharField(choices=[('primary', 'Primary (Ages 2-10)'), ('secondary', 'Secondary (Ages 11-17)')], max_length=20)),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('brain_skills_score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cohort', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.cohort')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='core.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-enrollment_date'],
            },
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
                ('children', models.ManyToManyField(related_name='parents', to='core.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lab_Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('graded', 'Graded')], default='not_started', max_length=20)),
                ('submission_content_url', models.URLField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.instructor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.lab_project')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_submissions', to='core.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HardwareAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_type', models.CharField(choices=[('ipad', 'iPad (NeuroArt)'), ('openbci_kit', 'OpenBCI Hardware Kit'), ('laptop', 'Laptop (Core i7)')], max_length=20)),
                ('mac_address', models.CharField(max_length=17, unique=True)),
                ('device_id', models.CharField(blank=True, max_length=50)),
                ('serial_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('maintenance', 'Maintenance'), ('decommissioned', 'Decommissioned')], default='available', max_length=20)),
                ('is_online', models.BooleanField(default=False)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
                ('instructor_override_reason', models.TextField(blank=True)),
                ('override_active_until', models.DateTimeField(blank=True, null=True)),
                ('purchased_date', models.DateField()),
                ('purchase_cost_naira', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hardware_assets', to='core.school')),
                ('assigned_to', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_hardware', to='core.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CBT_Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('graded', 'Graded'), ('expired', 'Expired')], default='not_started', max_length=20)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('last_auto_save', models.DateTimeField(blank=True, null=True)),
                ('auto_saved_answers', models.JSONField(default=dict)),
                ('final_answers', models.JSONField(blank=True, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('jwt_token', models.CharField(blank=True, max_length=500)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.cbt_quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbt_sessions', to='core.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('parent', 'Parent'), ('instructor', 'Instructor'), ('school_admin', 'School Administrator'), ('super_admin', 'Super Admin (DBBSA)')], max_length=20)),
                ('digital_id', models.CharField(max_length=20, unique=True)),
                ('allowed_domains', models.CharField(help_text='Comma-separated allowed domains: dbbsa.com, admin.dbbsa.com, sys.neuralvillage.com', max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('requires_2fa', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'is_active'], name='core_studen_school__cef4ba_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['cohort'], name='core_studen_cohort__630723_idx'),
        ),
        migrations.AddIndex(
            model_name='lab_submission',
            index=models.Index(fields=['status'], name='core_lab_su_status_f8f1f8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lab_submission',
            unique_together={('student', 'project')},
        ),
        migrations.AddIndex(
            model_name='hardwareasset',
            index=models.Index(fields=['school', 'status'], name='core_hardwa_school__54e189_idx'),
        ),
        migrations.AddIndex(
            model_name='hardwareasset',
            index=models.Index(fields=['assigned_to'], name='core_hardwa_assigne_2af143_idx'),
        ),
        migrations.AddIndex(
            model_name='cbt_session',
            index=models.Index(fields=['status'], name='core_cbt_se_status_f3e509_idx'),
        ),
        migrations.AddIndex(
            model_name='cbt_session',
            index=models.Index(fields=['student', 'status'], name='core_cbt_se_student_c7e19f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cbt_session',
            unique_together={('student', 'quiz')},
        ),
        migrations.AddIndex(
            model_name='user_profile',
            index=models.Index(fields=['role'], name='core_user_p_role_a894ad_idx'),
        ),
        migrations.AddIndex(
            model_name='user_profile',
            index=models.Index(fields=['digital_id'], name='core_user_p_digital_2c4fe5_idx'),
        ),
    ]
