# Generated by Django 6.0.5 on 2026-05-28 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_attendancesession_attendancerecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'Student'), ('parent', 'Parent'), ('instructor', 'Instructor'), ('school_admin', 'School Administrator'), ('super_admin', 'Super Admin (DBBSA)')], default='instructor', max_length=20)),
                ('event_type', models.CharField(choices=[('page_view', 'Page View'), ('navigation', 'Navigation'), ('button_click', 'Button Click'), ('form_submit', 'Form Submit'), ('attendance_action', 'Attendance Action'), ('cohort_view', 'Cohort View'), ('school_view', 'School View')], max_length=32)),
                ('target_model', models.CharField(blank=True, max_length=64)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('target_label', models.CharField(blank=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navigation_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
