# Generated by Django 6.0.5 on 2026-05-31 23:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_navigationevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationevent',
            name='event_type',
            field=models.CharField(choices=[('page_view', 'Page View'), ('navigation', 'Navigation'), ('button_click', 'Button Click'), ('form_submit', 'Form Submit'), ('login', 'Login'), ('attendance_action', 'Attendance Action'), ('cohort_view', 'Cohort View'), ('school_view', 'School View')], max_length=32),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=4500.0, max_digits=10)),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('description', models.CharField(default='KNSB 2026 Term Tuition', max_length=255)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid'), ('FAILED', 'Failed')], default='UNPAID', max_length=20)),
                ('due_date', models.DateField(default=django.utils.timezone.now)),
                ('gateway', models.CharField(choices=[('PAYSTACK', 'Paystack'), ('REMITA', 'Remita')], default='PAYSTACK', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TransactionWebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway', models.CharField(choices=[('PAYSTACK', 'Paystack'), ('REMITA', 'Remita')], max_length=20)),
                ('reference_code', models.CharField(max_length=150)),
                ('payload_dump', models.JSONField(blank=True, default=dict)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='core.invoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='core_invoic_status_3d8780_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='core_invoic_due_dat_a17de6_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['payer_user'], name='core_invoic_payer_u_176865_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionwebhooklog',
            index=models.Index(fields=['gateway'], name='core_transa_gateway_cd7462_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionwebhooklog',
            index=models.Index(fields=['reference_code'], name='core_transa_referen_40823b_idx'),
        ),
    ]
