# Generated by Django 6.0.5 on 2026-06-01 01:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_navigationevent_event_type_invoice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payer_email',
            field=models.EmailField(blank=True, help_text='Email used for payment when payer is not yet a system user', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.student'),
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('dob', models.DateField(blank=True, null=True)),
                ('role_requested', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('AWAITING_DETAILS', 'Awaiting Details'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PROVISIONED', 'Provisioned')], default='PENDING', max_length=32)),
                ('payment_reference', models.CharField(blank=True, max_length=150)),
                ('temp_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('temp_token_expires', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entries', to='core.invoice')),
                ('target_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.school')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='core_waitli_status_e1a1f2_idx'), models.Index(fields=['email'], name='core_waitli_email_4321a2_idx'), models.Index(fields=['payment_reference'], name='core_waitli_payment_81b542_idx')],
            },
        ),
    ]
