services:
  - type: web
    name: dbbsa-django
    env: python
    plan: starter
    region: oregon
    branch: main
    autoDeploy: true
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate --noinput && gunicorn neural_village.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHONUNBUFFERED
        value: '1'
      - key: DJANGO_SETTINGS_MODULE
        value: neural_village.settings
      - key: ALLOWED_HOSTS
        value: '*.onrender.com'
    healthCheckPath: /
    databases:
      - name: dbbsa-db
  - type: postgres
    name: dbbsa-db
    plan: starter
    databaseName: neural_village
    region: oregon
