services:
  - type: web
    name: dbbsa-django
    env: docker
    region: oregon
    branch: main
    autoDeploy: true
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHONUNBUFFERED
        value: '1'
      - key: DJANGO_SETTINGS_MODULE
        value: neural_village.settings
      - key: ALLOWED_HOSTS
        value: '.onrender.com,admin.dbbsa.com,sys.neuralvillage.com,dbbsa.com,portal.neuralvillage.com'
    healthCheckPath: /
    databases:
      - name: dbbsa-db
  - type: postgres
    name: dbbsa-db
    plan: starter
    databaseName: neural_village
    region: oregon
